manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: patrick-schultz
      url-base: https://github.com/patrick-schultz
    - name: adaptive-keys
      url-base: https://github.com/klausweiss
  projects:
    - name: zmk
      remote: patrick-schultz
      revision: main
      import: app/west.yml
  self:
    path: config
